apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_PASSWORD: AgBJS7cxppSwe29yKx2ObYmQMYEswdydIFeFNYzNiD8lx2FN/k1nEvX9+wRm49Fprrvmgo6ssj+KtirhdM7i+Y/KtGFXiAAkeCAuAoW3y0lLb/h/+C+KM/BpnFS7dxesBzn7XQ0ersrLOAzb/BWOPKQ4aEW3PBcRB6IQ2k4F6xohbmCkdJIz0OxPT2NPdDaIPkKxtLgfcbK15/EoN6ESDiBdQqGbvuTUjvfyMyw35b8EsejxxHRNgRAF8Rafa+p3Ft5okdt7+BkI1xWc8q/oFgp4xSLKf7AzDDQ1w4ro9uwT6T0CfS2p/lw2dTw4k3cqqJrVlISUsU3bIvJCiS3SgJxWDafk8iAnA8q9bfOb6hdrkavUwa/nvrrO2vRLNhVAmDtn/njgxBz6dAwHvb+QGj8T0eR1UO6nRJoqrPt5d0pm329fC9UAuzgbxtyLl/cNR+ENUUxI5rmROv11sDMcfrgP3IbiBsWUemAR87YdnBPlRkR4WgewhxL4FXS+IVcKV/AsF6ZBzbisKob9ETRtFbFcqSxXdfo8/x3gTxEPFK4wet0fzfGLumGsZjBDbCuI+Ngrh/BkysPe5fgDUKKLjENJKhhqlbI0x+jbMaujSXSAY80/cyPkcS5WaH6+DtnEdZtHDT2kgE2zAaf1dakHHfQw1qN4VyaAgO7p9nzx30f+6ZQ0x6LhoNBTc3P3rxLrGjgCfXC8jnO51g==
    ARTIFACTORY_URL: AgAxuBwOusiCpLnh+Bmk4R4uHZAdIpDjQx9mU71v7Mw0mTB4RAaBfvUaZE2/c91sIaFeabhK9VX7TAEOE8Ei1u/xXRDipx2UQek0CO4qLLZNsEigSBR6vd6jq1GAIRtSMk1UuaMHGjzB96ojnu5EJRROM//qayn1rKF/mUJACbJMdY+e5XQjOwY1fVAwhlhYau2j64YBFSahLIdKq1OX5Pot32Zu7RL1h39DF0LaSacxmWx0QVNmyo6PPD32m5FQtYA4VKDV0WUzvv6g7NKOz861e4aYJtUlEWEOwJp7QXZ3B9uvLNHyHjkJO9HY2ob91MEJ2Kh96wdCsgQVRUEZwonSeW4cbAoIrJRlsI+PIpHhPL5Ur4AbJ4h7idOBqBHIXDWOZt+L0Bj4ZbAuIHUkl14VfRWKYNru//bCH/tYkSloYT6faJQKSkRp9oClG7EE1GAEnF0XiOGbhNdRnXAfNfJC3Pvk86u62/QHwUFGqfGjPm3C90gsoc1CuxOj3s3502p4wC6tMx/OL/V7JHcSPDAjNH0DacagVw6exKCeh6b/u1xudwEudQP/f6puJQe8U55mhjYT5wlMHWUn3PZFo8mvsDgfoMgH+C8p5A6f2EBO6U7TypO4WeM+tRlv5cTPU2pWSA1mrJwGZrzry25opryP7rOh3xLrHFccwFO/D+LApb25z4tsLLwIVny5XjL1sSxihqFRpBH3b48jxf4qkz4jUu+Yyuk9EwFKrIWetY77baFL+7cVd+nb3g==
    ARTIFACTORY_USER: AgBY9XCFnhbGV/TituV5yYqzLBoDLBmndTyj4HMKrQARaolcyCrfuVqRu6n22211JOoDoVIMczZymAAY2BZHurdVD6yz2VSEhtr5PPbb4KHvVCB5gU6YlLHbsToleUQWhwh7FhgMR1gLSkGSyAU72hisNGymiRwFdtK/7ScYKnTpSyisjg+Bw9tBIZeIZchta2TUPeq04adOxuvdEXyPCX6CWazHqRssyX6I02VAoGpdoQ7Bba/3zvPfc9sOTD3AQoZOXP8yDjoyNTA5PlIOAn3LcWwADzGZ14X9tWxGBWQPnYvOXIPbNxMVmz3nQ6o1WgvNJwJHl5xdJ03dwkqN2cRLsgnHN7VyHa+4HuLdvsG9YWzD1zG6QFFluXk7BmrqtDnOgkd871eIOv5chTM7M43fyzsSk2PG0bHbBLLEP53G25nyxwiEAA/Vol8JcLWyHzw2IyZIFuQpUoWJtv8u7v3nEFWE2IgF6QJM2AR8zstGo/Yd6NO24dDg1yyYjugN+hbWqCjNhWRLbGgloRihkExJYoF0HV5bfJO5pBu6/dk3by+yM0uQhK1RmDKivi6AsrurMXFT6gcKfDpbJOJgWCGeKxvvS9CMVrwiUg45QaJ1xK1eUf4wBq2GOlBYPDe5/AGCJwEZrwEknRUuN7udL52ZfMua81IiTbJ0bC74RNdyvlXeOrUJuJOit6Txv1s+jfAvL93dYg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:ownerReferences:
              .: {}
              k:{"uid":"58eae70e-6491-4284-8255-be546375a589"}:
                .: {}
                f:apiVersion: {}
                f:controller: {}
                f:kind: {}
                f:name: {}
                f:uid: {}
          f:type: {}
        manager: controller
        operation: Update
        time: "2021-10-22T21:51:47Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

