apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAXMNiXtuEdZHpowB8mw4cYkS6KZxYE670CbPaWxKMSEDJhiIBnE0CIJvo2RHqjVXkof4n/ST/huCTA8GrVkh4YFe0fW8o8Kx2Up1qRgAEnkOSOyLS9rkmDimJc09xGKS6fm1ogQaaHWS1Wn95il/L0gcpf9eu1FJ+vePfEQ37NtuK3xHzT8fkj4CEPi8Y2lB18QMeAna0UljRCRoQqs6nl7VxxWFuKuuQknPqSJP2MMB44sDt+sexuYZgVkrJL56cg2JCGNHYbKIeaGkFQyumx4xlzbmWfHmmGzd2AVuWhx5TXk1rtKtkjtG8MG4EAXeTGuvQ31ZZ6dOiaN8xHQ757x7y97yNTVPUb+a2kW49ZNsvxkxHTXzHkGwX9kYdInXqVdZeLniyd9Aq2cquSH+/peTucKB691c8kOQS5qj9dMMjt37ZasETM60PoUd+0OOfbc1gJ1CNBtKyd92PNktG2cRmFcKOTOnty7MCRD2ahNHAu4CAbV1FE0Dhj66HwiDM7f1UQEu8Ve6Ai8/aF1yHbUxVJmumA9IoysefszhgU7A1GNSfNgaKraIXRxYYn3Ier3u+3gKSrDz754ZJ3bNj1g1O3zgxV7DUv26oF2qPWA+Vk1KYreEwV694TpTPQNdpsLyXYJ4It9SeGjSHChYnrVz3Ey5gdvnzpOEjj+fEpfHOGk0cZWrVmb0MI3pVTuHoBumCIRI3IUF/JZm0buO2K89xEqoBcXiLPtoA=
    ARTIFACTORY_PASSWORD: AgAE6fT1M3u8QcW1+l5d/6I2/yf7MsYbX511/ENGEPH8vR0ZMXIG2s3clBKajcCT0+ZAlDjAN4QBZqUxnShpEFNluQicbw7d5cxjpyBkKF6rMO6fSAco7Mt1Y2UDG3dHQ1hnP29XnmQWlU0qJImGuHenpBdWjkXzfqDCEAIMbv7RnsEcSZcJtfaBRYOYiow/XDDQGDFuM+lizGpy5tu1bhYBbf+Do5UB+90XqoYfyuUEPLtdg0pXE3YqAMDwYsnYomHwI3Zjiiu4N3ND3zwOLN9cyc4TH07MB08WHJtnQ070SLaoom7rL2Zrsx49J0+WoqNBo+bnmGkFRw53f+2vcUz5VPFMqRzCASb/ZcLqwOMvJznwPEqPGSJqr4xl8ImHITGTG93S031OyKzPFDF+ePJ4CJ+LEDCwEwXsefpya35D3JPrjWtI8S3kmG0ycUMU0FSZbCq6jPNF489mmmdfDDG4ivtiM2dblpwY2jVJFmKubaqMcBBzDpaKJen6bUW8ozCPmUc0xjTKQGF8kFj+MA1r2vaEpp29+7cLLJcq+2ZceE6nQTGI8cGE6pxhSsUiqbWVnweIke84HnTbqQHxoMznZHn3BvHwPnvP2aBA1l/l7MWA8tXYr7BUqbnBlT+db12wxIFM6TVPXj8yflO+Ydhg7N9k7Elhb+aLEfVyjmv3ODRj+E11AjNyO/ZG5nJHuLZyr4uN5NKm640=
    ARTIFACTORY_URL: AgCHdDdni+wcuCkCacbrY3fGZKj84DkYCH2TX5gwGy5lLtYAY640RMz/Y3clznA0BLwhx8H2FE9DrH+P05nXlrmVZfJJ19Vnde0M/0FiFaEdc7NyPQ85tQwwybUXqVR+wFeblvDyV07Ie9rtUlfTkANafo80c153KVvg/Qzj+AtxG40CMUU1Jt0tgRrB0cwayQ+5DEs25OG/gKHbTHQhtjtHAYtl3Vtlar3Xoi0imvKGdGNCDpUePdGKotq//aJx7JN1jwzSVUgu21Dx4Bmp0+qIU++TnW2DFeWIuBMNr6wJ8O5jjbxJHsrwF9rfDKdRLctDOCsWh3oCgNBC2tO9ltwkQkAuTBFwVKFiaxyjBJ5smJZeTNLmosgTteZrxW65EVlHL9/cdaT+45OHmynxSHKtO06mlLIGye3V0t3cO/pEN+GHb1x09Bp2h10gs0VfUSVYuDCMTzZwAczjxtNi9SvGQ5rJMGw+tp+oEx0MqA86Y6XfbLADRw9h4MU3zi0uJWoqhY8KHt8nq7PXjZ81e7HHdJ62cBHsvHenUO6BFWo6R2YPpBLeiwcFR7GwYmtVtqrgf62yhDFq3pLwGTUpxkJY3HoAG1NfQCGNAY73/aSj1XTtWNistU2LRDVNuph6SNCAYyobPbpCqmrRTrrOz7c4C4ZzwzDnxfqdKtT26qv8vwZnZ+ImjHGlMVEQ7RHgKY2HpcjBL3DEpBBPPtZ77Dq7eVmwSb//fYxIJ++LWeLrs1XAsquS+VXojQ==
    ARTIFACTORY_USER: AgC5SNKa1uN/VuSYGmrY3hSojuAUNY6FROsey/tmR+xOOKqt8m3/nHl0y+0ZAepAOZN4TSI/6tYgKRWpiHq1Zu/KMaTjtYkanQw7Kso/NTPzAJUcCDi62poWMp2Jt6EbuG5bWZ+gPIAGdJiDR38KQnRiEmCDZnWdZtJYXED9fvrHyb4acHG0+X03NWdPpEj/s/XYbBzhGjAFhMLfZ7Y1qfWayyAAer+Ys2Il1zJULOva4l+HEF/D1Agh1GUBEwwgh55FQJFMyKJGkTNw+IUU/ZA957jJnZYTzIvcaOZKNNNEaqtj/xOihsMMjpP24oAyF1YnF+gBDDXeBVA6h5S/1dIoCXE52mcjPpQORGMkK3eomk65A4tYzrTTalhC5BLRCWADv+WUjiJMjgf/3cdLPoSKMsqCDn94EaROhl9YmmBYOhYcWruipvDX4eDoEAtQzqKoMcd5SyXho2yNaNr1xD6cxfO0tHV812j7fcR9E2JtMMrWeEHdkIAmiTwAizwFqJ7JudCpNcBNC8s/CBWvhQqgfwVvs1Y2a6OZANVLNS12G4W2jD+G40VO8dZxq+XbtRb386AFHa/qPqMugZKDSAnPCXmyRNrNxPmkeF7T5eeyXeDkTt9QruHcLvUGJafqSjyZXPbRLIyHkmF7a5FwR8M15MGK+BgYPU+PxutSpzpxGEivVMxM2NCYN0j67K8GuEDHDoGEMg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-10-21T19:04:17Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
        manager: Mozilla
        operation: Update
        time: "2021-10-25T17:00:48Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

